spring:
  application:
    name: ourphotos

  flyway:
    enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:${H2_PATH};AUTO_SERVER=TRUE;TCP_ALLOW_OTHERS=FALSE
    username: ${H2_USER}
    password: ${H2_PWD}

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create